/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    copy: typeof import('./components/svg/SvgArrow copy.vue')['default']
    PageFooter: typeof import('./components/page/PageFooter.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionDesc: typeof import('./components/SectionDesc.vue')['default']
    SvgArrow: typeof import('./components/svg/SvgArrow.vue')['default']
    SvgCart: typeof import('./components/svg/SvgCart.vue')['default']
    SvgFacebook: typeof import('./components/svg/SvgFacebook.vue')['default']
    SvgGithub: typeof import('./components/svg/SvgGithub.vue')['default']
    SvgInstagram: typeof import('./components/svg/SvgInstagram.vue')['default']
    SvgLogo: typeof import('./components/svg/SvgLogo.vue')['default']
    SvgMail: typeof import('./components/svg/SvgMail.vue')['default']
    SvgMenu: typeof import('./components/svg/SvgMenu.vue')['default']
    SvgTwitter: typeof import('./components/svg/SvgTwitter.vue')['default']
    UiButton: typeof import('./components/ui/UiButton.vue')['default']
  }
}
